### ISSUE TITLE
Groundtruth of SMPL shape and pose?

### ISSUE THREAD

**Issue by mikecheninoulu** [kzhou23/shape_pose_disent#4]
Hi, dear Zhou,

Thanks for your impressive work, I currently want to reproduce your work, but I cannot get the groundtruth SMPL shape and pose, especially from FAUST and DFAUST datasets (only the mesh is available). Could you indicate with more details how to get the groundtruth SMPL shape and pose?

**Comment by kzhou23** [comment]
Hi,

I did not evaluate on FAUST and DFAUST because SMPL parameters are not available. If you really want to do so, it won't be too difficult to solve for the groundtruth parameters by fitting SMPL model to each registered scan. The optimization problem should converge to the global minimum pretty quickly.

**Comment by mikecheninoulu** [comment]
Hi,
Thanks for your reply! I thought there are existing ground truths for SMPL parameters.
Then I will obtain the SMPL parameters following your way, many thanks!
